version: '3.8'

services:
  ipfs_host:
    image: ipfs/kubo:latest
    container_name: ipfs_host
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    volumes:
      - ${ipfs_staging}:/export
      - ${ipfs_data}:/data/ipfs
    restart: unless-stopped

  ipfs_secondary:
    image: ipfs/kubo:latest
    container_name: ipfs_secondary
    ports:
      - "4002:4001/tcp"
      - "4002:4001/udp"
      - "127.0.0.1:5002:5001"
      - "127.0.0.1:8081:8080"
    volumes:
      - ${ipfs_staging_secondary}:/export  # Assuming different staging directory
      - ${ipfs_data_secondary}:/data/ipfs  # Assuming different data directory
    restart: unless-stopped
